plugins {
    id 'java'
}

description '安全权限'

dependencies {

// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-security
    api('org.springframework.security:spring-security-core')

    api('org.springframework.security:spring-security-config')

    api('org.springframework.security:spring-security-rsa')

    api('org.springframework.security:spring-security-crypto')

    // https://mvnrepository.com/artifact/com.azure/azure-identity
//    api("com.azure:azure-identity:${identityVersion}"){
//        transitive(true)
//    }

//    // https://mvnrepository.com/artifact/com.microsoft.azure/msal4j
//    api("com.microsoft.azure:msal4j:${msal4jVersion}") {
//        transitive(true)
//    }
//
//// https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-authorization-server
//    api("org.springframework.security:spring-security-oauth2-authorization-server:${springSecurityOauth2AuthorizationServerVersion}") {
//        transitive(true)
//    }

    // https://mvnrepository.com/artifact/org.jboss.aerogear/aerogear-otp-java
    api("org.jboss.aerogear:aerogear-otp-java:${aerogearOTPVersion}"){
        transitive(true)
    }


// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-oauth2-resource-server
    api('org.springframework.boot:spring-boot-starter-oauth2-resource-server') {
        transitive(true)
    }

// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-oauth2-client
    api('org.springframework.boot:spring-boot-starter-oauth2-client') {
        transitive(true)
    }

    api('org.springframework.security:spring-security-remoting'){
        transitive(false)
    }

    api project(':events')

}

test {
    useJUnitPlatform()
}
