plugins {
    id 'java'
}

description '存储'

dependencies {

    runtimeOnly('mysql:mysql-connector-java:8.0.33')

    implementation('com.mysql:mysql-connector-j') {
        transitive(false)
    }
    implementation('org.postgresql:postgresql') {
        transitive(false)
    }
    implementation('com.baomidou:mybatisplus-spring-boot-starter') {
        transitive(false)
    }
    implementation('com.baomidou:mybatis-plus-boot-starter') {
        transitive(false)
    }
    implementation('com.baomidou:dynamic-datasource-spring-boot-starter'){
        transitive(false)
    }
    implementation 'p6spy:p6spy'
}

test {
    useJUnitPlatform()
}
